name: artrooms
description: Artrooms Flutter App.
version: 1.0.8+4

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1
  url_launcher: ^6.3.0
  sendbird_sdk: ^3.2.20
  intl: 0.18.1
  http: ^0.13.3
  shared_preferences: ^2.0.15
  image_picker: ^1.0.7
  file_picker: ^6.0.0
  photo_view: ^0.14.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.2
  photo_manager: ^3.0.0
  flutter_local_notifications: ^16.3.2
  scrollable_positioned_list: ^0.2.0
  focused_menu: ^1.0.5
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  channel_talk_flutter: ^2.6.2
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  flutter_keyboard_size: ^1.0.1
  flutter_svg: ^2.0.9
  flutter_linkify: ^5.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/profile/
    - assets/images/chats/
    - assets/images/photos/
    - assets/fonts/pretendard/
    - assets/fonts/suit/
    - assets/locale/symbols/
    - assets/sounds/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
    - family: SUIT
      fonts:
        - asset: assets/fonts/suit/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/suit/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/suit/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/suit/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/suit/SUIT-ExtraBold.ttf
          weight: 800
    - family: Gmarket Sans
      fonts:
        - asset: assets/fonts/gmarket/GmarketSansBold.otf
          weight: 500
