name: artrooms
description: Artrooms Flutter App.
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1
  url_launcher: ^6.1.14
  sendbird_sdk: ^3.0.11
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.15
  image_picker: ^1.0.7
  permission_handler: ^10.2.0
  # flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/profile/
    - assets/images/chats/
    - assets/images/photos/

#  fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
